sudo: false
language: scala
jdk:
  - openjdk8
scala:
  - 2.11.12

notifications:
  email:
    recipients:
      - markus.freudenberg@eccenca.com
    on_success: change
    on_failure: change
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
  
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "project workbench" universal:package-zip-tarball
